### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by KyleTryon** [Testlio/testlio-circleci-orb#2]
Hello Testlio team,

I am Kyle from the @circleci team. Thanks for sending in your orb. I took a look, and everything looks really great. I have outlined a short few review items to check into below.

* Remove the executor
    * The provided executor is the same as what comes with the Node orb and could should be removed and instead, potentially added in directly to the `schedule-run` job if this job always requires node.
    * Executors are mostly useful when providing an executor, like an image with custom software.
    * The element of the executor here is not intended to be used elsewhere it seems and so does not need to be reusable.
* Set `token` "type" to `env_var_name`
    * https://circleci.com/docs/2.0/orb-author-faq/#secure-api-tokens
* Job `schedule-run`
    * Attaching the workspace appears to be optional, and off by default. Without a workspace, will a checkout step be needed?
* Usage example
    In your usage example, the jobs is called in a workflow and I see `attach workspace` is set to true, but there are no other jobs in the workflow. Should there be a sample of a job that would run before `schedule-run`?

**Comment by eloypnd** [comment]
@KyleTryon thanks for your feedback.

We have addressed your comments in the following PR: #3. PTAL.
